PROGS_CXX = test
SRCS     = main.cpp
MK_MAN   = no
NO_OBJ   = noobj

CXXFLAGS += -g -std=c++17 -pedantic -Wall -Wextra -DSPDLOG_FMT_EXTERNAL -I/usr/local/include
LDFLAGS  += -L/usr/local/lib -lspdlog -lfmt

.include <bsd.progs.mk>
